---
- name: install httpd
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: start httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: open firewall
  ansible.posix.firewalld:
    service: http
    state: eabled
    immediate: true
    permanent: true
